type fruitNames =
  | 'cranberry'
  | 'blueberry'
  | 'pineapple'
  | 'apple'
  | 'banana'
  | 'passion'
  | 'orange'
  | 'cherry'
  | 'grapefruit'
  | 'grapes'
  | 'rhabarber'
  | 'peach'
  | 'pomegranate'
type IconNames =
  | 'dressing'
  | 'burger'
  | 'steak'
  | 'vegan'
  | 'kleinigkeiten'
  | 'salat'
  | 'eis'
  | 'flammkuchen'
  | 'kinder'
  | 'klassik'
  | 'desserts'
  | 'softdrinks'
  | 'beer'
  | 'wine'
  | 'hardLiquor'
  | 'shot glass'
  | 'juice'
  | 'tea'
  | 'coffee'
  | 'cocktail'
  | 'longdrink'
  | 'dishes'
  | 'drinks'

// Softdrinks brand names
type BrandNames =
  | 'Coca Cola'
  | 'Fanta'
  | 'Sprite'
  | 'Fritz-kola'
  | 'Voelkel BioZisch'
  | 'Pepsi'
  | 'Thomas Henry'
  | 'Red Bull'
  | 'Paloma'
  | 'Magnus Imperial'
  | 'Hausgemachtes'
  | ''
  | 'Bitburger'
  | 'König Ludwig'
  | 'Ratsherrn'
  | 'Fahrbier'
  | 'Vitamalz'
  | 'Oatly'
  | 'Alpro'
type AllergenLabel =
  | 'Enthält glutenhaltige/s Getreide/-Erzeugnisse'
  | 'Enthält Ei/-Erzeugnisse'
  | 'lactoseFrei'
  | 'Vegan'
  | 'Glutenfrei'
  | 'Gerste'
  | 'Weizen'
  | 'Nüsseehältig'
  | 'Enthält Milch/-Erzeugnisse (laktosehaltig)'
  | 'Enthält Senf/-Erzeugnisse'
  | 'Enthält Sellerie/-Erzeugnisse'
  | 'Enthält Sojabohnen/-Erzeugnisse'
  | 'Enthält Lupine/-nerzeugnisse'
  | 'Enthält Sesamsamen/-Erzeugnisse'
  | 'Enthält Schwefeldioxid/Sulfite'
  | 'Enthält Fisch/-Erzeugnisse'
  | 'Enthält Erdnüsse/-Erzeugnisse'
  | 'Dinkel'
type additivesLabel =
  | 'Mit Farbstoff'
  | 'Mit Phosphat'
  | 'Enthält Krebstiere/-Erzeugnisse'
  | 'Konservierungsstoffen'
  | 'Mit Antioxidationsmittel'
  | 'enthält Stabilisatoren'
  | 'Mit Nitritpökelsalz'
  | 'Mit Süßungsmittel(n)'
  | 'Mit Geschmacksverstärker'
  | 'Mit Säuerungsmitte'
  | 'Geschwärzt'
type eatStyle = 'Vegan' | 'Halal'
